import { query } from "@/lib/db";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

export async function GET(
  request: Request,
  {
    params,
  }: {
    params: {
      id: string;
    };
  }
) {

  const patientId = params.id;

  const patient = await query(
    `
    SELECT *
    FROM patients
    WHERE id = $1
    `,
    [patientId]
  );

  const recovery = await query(
    `
    SELECT *
    FROM recovery_scores r
    JOIN therapy_sessions t
      ON t.id = r.session_id
    WHERE t.patient_id = $1
    ORDER BY r.id ASC
    `,
    [patientId]
  );

  const ai = await query(
    `
    SELECT *
    FROM ai_recommendations
    WHERE patient_id = $1
    ORDER BY id ASC
    `,
    [patientId]
  );

  const p = patient[0];

  if (!p) {

    return new Response(
      "Patient not found",
      {
        status: 404,
      }
    );

  }

  const pdfDoc =
    await PDFDocument.create();

  const page =
    pdfDoc.addPage([595, 842]);

  const font =
    await pdfDoc.embedFont(
      StandardFonts.Helvetica
    );

  let y = 800;

  page.drawText(
    "STRIVE THERAPY REPORT",
    {
      x: 50,
      y,
      size: 20,
      font,
      color: rgb(0, 0, 0),
    }
  );

  y -= 40;

  page.drawText(
    `Nama Pasien : ${p.full_name}`,
    {
      x: 50,
      y,
      size: 12,
      font,
    }
  );

  y -= 20;

  page.drawText(
    `Usia : ${p.age ?? "-"}`,
    {
      x: 50,
      y,
      size: 12,
      font,
    }
  );

  y -= 20;

  page.drawText(
    `Gender : ${p.gender ?? "-"}`,
    {
      x: 50,
      y,
      size: 12,
      font,
    }
  );

  y -= 20;

  page.drawText(
    `Diagnosis : ${p.diagnosis ?? "-"}`,
    {
      x: 50,
      y,
      size: 12,
      font,
    }
  );

  y -= 40;

  page.drawText(
    `Total Recovery Record : ${recovery.length}`,
    {
      x: 50,
      y,
      size: 12,
      font,
    }
  );

  y -= 40;

  page.drawText(
    "Recovery History",
    {
      x: 50,
      y,
      size: 16,
      font,
    }
  );

  y -= 25;

  if (recovery.length === 0) {

    page.drawText(
      "Belum ada data recovery",
      {
        x: 70,
        y,
        size: 12,
        font,
      }
    );

    y -= 20;

  } else {

    recovery.forEach(
      (r: any, index: number) => {

        page.drawText(
          `Sesi ${index + 1} : Score ${r.score}`,
          {
            x: 70,
            y,
            size: 12,
            font,
          }
        );

        y -= 20;

      }
    );

  }

  y -= 20;

  page.drawText(
    "AI Recommendation",
    {
      x: 50,
      y,
      size: 16,
      font,
    }
  );

  y -= 25;

  if (ai.length === 0) {

    page.drawText(
      "Belum ada rekomendasi AI",
      {
        x: 70,
        y,
        size: 12,
        font,
      }
    );

    y -= 20;

  } else {

    ai.forEach(
      (a: any) => {

        page.drawText(
          `• ${a.recommendation}`,
          {
            x: 70,
            y,
            size: 12,
            font,
          }
        );

        y -= 20;

      }
    );

  }

  y -= 30;

  page.drawText(
    `Generated At : ${new Date().toLocaleString()}`,
    {
      x: 50,
      y,
      size: 10,
      font,
    }
  );

  y -= 15;

  page.drawText(
    "Generated by STRIVE",
    {
      x: 50,
      y,
      size: 10,
      font,
    }
  );

 const pdfBytes =
  await pdfDoc.save();

const pdfBuffer =
  Buffer.from(pdfBytes);

return new Response(
  pdfBuffer as any,
  {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition":
        `attachment; filename="report-patient-${patientId}.pdf"`
    }
  }
);
}
